package com.lintang.netflik.paymentservice.entity;

public interface OutboxEventType {
    String VALIDATE_PAYMENT = "VALIDATE_PAYMENT";
    String VALIDATED_PAYMENT = "VALIDATED_PAYMENT";
    String ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION";
    String ADDED_SUBSCRIPTION = "ADDED_SUBSCRIPTION";
    String COMPLETE_ORDER = "COMPLETE_ORDER";
    String UPDATE_ORDER_PAID_FAIL = "UPDATE_ORDER_FAIL";
    String UPDATE_ORDER_COMPLETED_FAIL = "UPDATE_ORDER_COMPLETED_FAIL";
    String SUBSCRIPTION_ERROR = "SUBSCRIPTION_ERROR";


    String ADD_PAYMENT_ERROR = "ADD_PAYMENT_ERROR";
    String CANCELLED_PAYMENT = "CANCELLED_PAYMENT";
    String COMPENSATING_ORDER_SUBSCRIPTION_ERROR = "COMPENSATING_ORDER_SUBSCRIPTION_ERROR";


}
